region: ap-northeast-1
cluster: vacca-note
service: vacca-note
service_definition: ecs-service-def.json
task_definition: ecs-task-def.json
timeout: 10m0s
plugins:
  - name: tfstate
    config:
      url: s3://okawa-tfstate/vacca-note/cicd/main.tfstate